// Real-world-referenced material definitions for Grit.
//
// Each entry spreads MATERIAL_DEFAULTS (see materialSchema.js) and then
// overrides the fields that make the material distinct. Fields left to
// the default are ones that are genuinely close to the generic solid
// baseline for that material (e.g. neutral pH, baseline chemical
// reactivity) - not skipped out of laziness.
//
// Reference magnitudes (density kg/m^3, thermal conductivity W/(m*K),
// specific heat J/(kg*K), melting/boiling C, electrical conductivity
// S/m) are drawn from standard materials-science/chemistry reference
// values. Where a material's composition varies in reality (lava, wood
// species, steel alloys, bitumen...), a representative figure is used -
// this is a game sim dataset, not a materials-science reference, but
// magnitudes and relative ordering should be recognizably correct.

import { MATERIAL_DEFAULTS } from './materialSchema.js';

export const MATERIALS_DATA = [
  // ---------------------------------------------------------------
  // Liquids
  // ---------------------------------------------------------------
  {
    ...MATERIAL_DEFAULTS,
    id: 'water',
    name: 'Water',
    color: [0.25, 0.45, 0.85, 1.0],
    matterState: 'liquid',
    density: 1000,
    viscosity: 0.001,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.6,
    specificHeatCapacity: 4186,
    emissivity: 0.96,
    meltingPointC: 0,
    boilingPointC: 100,
    acidity: 7,
    electricalConductivity: 0.05,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'seawater',
    name: 'Seawater',
    color: [0.15, 0.4, 0.6, 1.0],
    matterState: 'liquid',
    density: 1025,
    viscosity: 0.00108,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.6,
    specificHeatCapacity: 3993,
    emissivity: 0.96,
    meltingPointC: -2,
    boilingPointC: 100.7,
    acidity: 8.1,
    solubility: 0,
    electricalConductivity: 4.8,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'crude_oil',
    name: 'Crude Oil',
    color: [0.05, 0.03, 0.02, 1.0],
    matterState: 'liquid',
    density: 870,
    viscosity: 0.008,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.14,
    specificHeatCapacity: 1970,
    emissivity: 0.9,
    meltingPointC: -30,
    boilingPointC: 350,
    chemicalReactivity: 0.2,
    ignitionTemperatureC: 250,
    burnRate: 0.7,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'motor_oil',
    name: 'Motor Oil',
    color: [0.1, 0.08, 0.05, 1.0],
    matterState: 'liquid',
    density: 900,
    viscosity: 0.2,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.145,
    specificHeatCapacity: 1670,
    emissivity: 0.9,
    meltingPointC: -20,
    boilingPointC: 300,
    ignitionTemperatureC: 350,
    burnRate: 0.5,
    electricalConductivity: 1e-12,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'honey',
    name: 'Honey',
    color: [0.78, 0.5, 0.08, 1.0],
    matterState: 'liquid',
    density: 1420,
    viscosity: 10,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.5,
    specificHeatCapacity: 2400,
    emissivity: 0.9,
    meltingPointC: null,
    boilingPointC: null,
    acidity: 3.9,
    solubility: 0,
    electricalConductivity: 0.03,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'mercury',
    name: 'Mercury',
    color: [0.75, 0.76, 0.78, 1.0],
    matterState: 'liquid',
    density: 13534,
    viscosity: 0.0015,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 8.3,
    specificHeatCapacity: 140,
    emissivity: 0.1,
    meltingPointC: -38.83,
    boilingPointC: 356.7,
    chemicalReactivity: 0.05,
    electricalConductivity: 1.04e6,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'blood',
    name: 'Blood',
    color: [0.5, 0.0, 0.05, 1.0],
    matterState: 'liquid',
    density: 1060,
    viscosity: 0.004,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.52,
    specificHeatCapacity: 3600,
    emissivity: 0.96,
    meltingPointC: -0.5,
    boilingPointC: 100,
    acidity: 7.4,
    electricalConductivity: 0.7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'lava',
    name: 'Lava',
    color: [0.9, 0.3, 0.05, 1.0],
    matterState: 'liquid',
    density: 3100,
    viscosity: 1e4,
    friction: 0,
    structuralStrength: 0.1,
    thermalConductivity: 2,
    specificHeatCapacity: 1200,
    emissivity: 0.9,
    meltingPointC: 1150,
    boilingPointC: null,
    electricalConductivity: 1,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'sulfuric_acid',
    name: 'Sulfuric Acid',
    color: [0.85, 0.85, 0.6, 1.0],
    matterState: 'liquid',
    density: 1840,
    viscosity: 0.024,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.34,
    specificHeatCapacity: 1380,
    emissivity: 0.9,
    meltingPointC: 10,
    boilingPointC: 337,
    acidity: 0.3,
    chemicalReactivity: 0.9,
    electricalConductivity: 25,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'mud',
    name: 'Mud',
    color: [0.32, 0.23, 0.14, 1.0],
    matterState: 'liquid',
    density: 1800,
    viscosity: 50,
    friction: 0.2,
    structuralStrength: 0.1,
    thermalConductivity: 1.3,
    specificHeatCapacity: 1500,
    emissivity: 0.9,
    meltingPointC: 0,
    boilingPointC: null,
    acidity: 6.5,
    absorptionCapacity: 0.3,
    electricalConductivity: 0.02,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'milk',
    name: 'Milk',
    color: [0.95, 0.93, 0.85, 1.0],
    matterState: 'liquid',
    density: 1030,
    viscosity: 0.002,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.55,
    specificHeatCapacity: 3900,
    emissivity: 0.94,
    meltingPointC: -0.5,
    boilingPointC: 100.5,
    acidity: 6.7,
    electricalConductivity: 0.4,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'ethanol',
    name: 'Ethanol',
    color: [0.88, 0.88, 0.8, 1.0],
    matterState: 'liquid',
    density: 789,
    viscosity: 0.0012,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.17,
    specificHeatCapacity: 2440,
    emissivity: 0.9,
    meltingPointC: -114,
    boilingPointC: 78.4,
    chemicalReactivity: 0.3,
    ignitionTemperatureC: 13,
    burnRate: 0.9,
    explosiveness: 0.3,
    electricalConductivity: 1.35e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'liquid_nitrogen',
    name: 'Liquid Nitrogen',
    color: [0.85, 0.92, 0.98, 1.0],
    matterState: 'liquid',
    density: 807,
    viscosity: 0.00016,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.14,
    specificHeatCapacity: 2040,
    emissivity: 0.9,
    meltingPointC: -210,
    boilingPointC: -196,
    electricalConductivity: 1e-14,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'molten_iron',
    name: 'Molten Iron',
    color: [1.0, 0.55, 0.15, 1.0],
    matterState: 'liquid',
    density: 6980,
    viscosity: 0.0055,
    friction: 0,
    structuralStrength: 0,
    thermalConductivity: 35,
    specificHeatCapacity: 820,
    emissivity: 0.35,
    meltingPointC: 1538,
    boilingPointC: 2862,
    electricalConductivity: 7.2e5,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'tar',
    name: 'Tar',
    color: [0.08, 0.06, 0.05, 1.0],
    matterState: 'liquid',
    density: 1100,
    viscosity: 1e5,
    friction: 0,
    structuralStrength: 0.1,
    thermalConductivity: 0.17,
    specificHeatCapacity: 1470,
    emissivity: 0.9,
    meltingPointC: 100,
    boilingPointC: null,
    ignitionTemperatureC: 400,
    burnRate: 0.3,
    electricalConductivity: 1e-11,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'wine',
    name: 'Wine',
    color: [0.42, 0.03, 0.13, 1.0],
    matterState: 'liquid',
    density: 990,
    viscosity: 0.0015,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.5,
    specificHeatCapacity: 4000,
    emissivity: 0.94,
    meltingPointC: -5,
    boilingPointC: 85,
    acidity: 3.5,
    burnRate: 0.1,
    electricalConductivity: 0.2,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'gasoline',
    name: 'Gasoline',
    color: [0.85, 0.75, 0.4, 1.0],
    matterState: 'liquid',
    density: 720,
    viscosity: 0.0006,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.15,
    specificHeatCapacity: 2220,
    emissivity: 0.9,
    meltingPointC: -40,
    boilingPointC: 100,
    chemicalReactivity: 0.4,
    ignitionTemperatureC: -43,
    burnRate: 1.0,
    explosiveness: 0.6,
    electricalConductivity: 1e-11,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'vinegar',
    name: 'Vinegar',
    color: [0.85, 0.82, 0.6, 1.0],
    matterState: 'liquid',
    density: 1010,
    viscosity: 0.0012,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.6,
    specificHeatCapacity: 4000,
    emissivity: 0.94,
    meltingPointC: -3,
    boilingPointC: 100,
    acidity: 2.5,
    electricalConductivity: 0.4,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'kerosene',
    name: 'Kerosene',
    color: [0.82, 0.75, 0.45, 1.0],
    matterState: 'liquid',
    density: 810,
    viscosity: 0.0016,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.15,
    specificHeatCapacity: 2000,
    emissivity: 0.9,
    meltingPointC: -40,
    boilingPointC: 175,
    ignitionTemperatureC: 50,
    burnRate: 0.8,
    electricalConductivity: 1e-12,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'antifreeze',
    name: 'Antifreeze',
    color: [0.6, 0.9, 0.2, 1.0],
    matterState: 'liquid',
    density: 1113,
    viscosity: 0.0161,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.26,
    specificHeatCapacity: 2400,
    emissivity: 0.9,
    meltingPointC: -13,
    boilingPointC: 197,
    ignitionTemperatureC: 400,
    burnRate: 0.2,
    electricalConductivity: 1e-6,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'lye',
    name: 'Lye Solution',
    color: [0.9, 0.93, 0.9, 1.0],
    matterState: 'liquid',
    density: 1250,
    viscosity: 0.004,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.6,
    specificHeatCapacity: 3300,
    emissivity: 0.9,
    meltingPointC: -25,
    boilingPointC: 145,
    acidity: 13.5,
    chemicalReactivity: 0.8,
    electricalConductivity: 22,
  },

  // ---------------------------------------------------------------
  // Rocks / minerals
  // ---------------------------------------------------------------
  {
    ...MATERIAL_DEFAULTS,
    id: 'granite',
    name: 'Granite',
    color: [0.65, 0.58, 0.55, 1.0],
    immovable: true,
    density: 2700,
    friction: 0.7,
    structuralStrength: 0.85,
    thermalConductivity: 2.9,
    specificHeatCapacity: 790,
    meltingPointC: 1215,
    electricalConductivity: 1e-8,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'basalt',
    name: 'Basalt',
    color: [0.2, 0.2, 0.22, 1.0],
    immovable: true,
    density: 3000,
    friction: 0.65,
    structuralStrength: 0.8,
    thermalConductivity: 2,
    specificHeatCapacity: 840,
    meltingPointC: 1150,
    electricalConductivity: 1e-6,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'obsidian',
    name: 'Obsidian',
    color: [0.05, 0.05, 0.07, 1.0],
    immovable: true,
    density: 2400,
    friction: 0.3,
    structuralStrength: 0.7,
    thermalConductivity: 1.2,
    specificHeatCapacity: 730,
    emissivity: 0.93,
    meltingPointC: 1100,
    electricalConductivity: 1e-12,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'marble',
    name: 'Marble',
    color: [0.92, 0.9, 0.88, 1.0],
    immovable: true,
    density: 2700,
    friction: 0.5,
    structuralStrength: 0.7,
    thermalConductivity: 2.08,
    specificHeatCapacity: 880,
    meltingPointC: 825,
    chemicalReactivity: 0.3,
    electricalConductivity: 1e-8,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'sandstone',
    name: 'Sandstone',
    color: [0.76, 0.62, 0.45, 1.0],
    immovable: true,
    density: 2300,
    friction: 0.6,
    structuralStrength: 0.55,
    thermalConductivity: 2.5,
    specificHeatCapacity: 920,
    meltingPointC: 1650,
    absorptionCapacity: 0.15,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'limestone',
    name: 'Limestone',
    color: [0.78, 0.76, 0.68, 1.0],
    immovable: true,
    density: 2600,
    friction: 0.55,
    structuralStrength: 0.5,
    thermalConductivity: 1.3,
    specificHeatCapacity: 900,
    meltingPointC: 825,
    chemicalReactivity: 0.3,
    absorptionCapacity: 0.1,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'quartz',
    name: 'Quartz',
    color: [0.9, 0.92, 0.95, 1.0],
    immovable: true,
    density: 2650,
    friction: 0.4,
    structuralStrength: 0.9,
    thermalConductivity: 7.7,
    specificHeatCapacity: 730,
    meltingPointC: 1670,
    electricalConductivity: 1e-14,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'diamond',
    name: 'Diamond',
    color: [0.85, 0.92, 0.95, 1.0],
    immovable: true,
    density: 3510,
    friction: 0.2,
    structuralStrength: 1.0,
    thermalConductivity: 2200,
    specificHeatCapacity: 509,
    meltingPointC: 3550,
    chemicalReactivity: 0.02,
    ignitionTemperatureC: 900,
    burnRate: 0.05,
    electricalConductivity: 1e-13,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'coal',
    name: 'Coal',
    color: [0.08, 0.07, 0.06, 1.0],
    immovable: false,
    density: 1350,
    friction: 0.5,
    structuralStrength: 0.3,
    thermalConductivity: 0.2,
    specificHeatCapacity: 1260,
    meltingPointC: null,
    ignitionTemperatureC: 400,
    burnRate: 0.6,
    electricalConductivity: 1e-3,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'slate',
    name: 'Slate',
    color: [0.25, 0.28, 0.32, 1.0],
    immovable: true,
    density: 2750,
    friction: 0.45,
    structuralStrength: 0.65,
    thermalConductivity: 2.0,
    specificHeatCapacity: 760,
    meltingPointC: 1200,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'pumice',
    name: 'Pumice',
    color: [0.72, 0.68, 0.62, 1.0],
    immovable: false,
    density: 500,
    friction: 0.6,
    structuralStrength: 0.2,
    thermalConductivity: 0.12,
    specificHeatCapacity: 850,
    meltingPointC: 1100,
    absorptionCapacity: 0.5,
    electricalConductivity: 1e-10,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'chalk',
    name: 'Chalk',
    color: [0.95, 0.94, 0.9, 1.0],
    immovable: false,
    density: 2200,
    friction: 0.6,
    structuralStrength: 0.15,
    thermalConductivity: 0.9,
    specificHeatCapacity: 900,
    meltingPointC: 825,
    chemicalReactivity: 0.3,
    absorptionCapacity: 0.2,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'flint',
    name: 'Flint',
    color: [0.3, 0.28, 0.26, 1.0],
    immovable: true,
    density: 2600,
    friction: 0.3,
    structuralStrength: 0.9,
    thermalConductivity: 1.5,
    specificHeatCapacity: 750,
    meltingPointC: 1670,
    electricalConductivity: 1e-13,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'clay_dry',
    name: 'Dry Clay',
    color: [0.72, 0.5, 0.38, 1.0],
    immovable: false,
    density: 1600,
    friction: 0.5,
    structuralStrength: 0.3,
    thermalConductivity: 0.8,
    specificHeatCapacity: 900,
    meltingPointC: 1200,
    solubility: 0.05,
    absorptionCapacity: 0.4,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'stone',
    name: 'Stone',
    color: [0.5, 0.5, 0.52, 1.0],
    matterState: 'solid',
    immovable: true,
    density: 2650,
    friction: 0.6,
    structuralStrength: 0.9,
    thermalConductivity: 2.5,
    specificHeatCapacity: 800,
    meltingPointC: 1200,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'shale',
    name: 'Shale',
    color: [0.3, 0.28, 0.25, 1.0],
    immovable: true,
    density: 2500,
    friction: 0.5,
    structuralStrength: 0.4,
    thermalConductivity: 1.5,
    specificHeatCapacity: 900,
    meltingPointC: 1100,
    absorptionCapacity: 0.05,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'halite',
    name: 'Rock Salt',
    color: [0.88, 0.85, 0.85, 1.0],
    immovable: false,
    density: 2170,
    friction: 0.4,
    structuralStrength: 0.35,
    thermalConductivity: 5.55,
    specificHeatCapacity: 850,
    meltingPointC: 801,
    boilingPointC: 1465,
    solubility: 0.9,
    electricalConductivity: 1e-7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'graphite',
    name: 'Graphite',
    color: [0.15, 0.15, 0.16, 1.0],
    immovable: false,
    density: 2260,
    friction: 0.15,
    structuralStrength: 0.25,
    thermalConductivity: 150,
    specificHeatCapacity: 710,
    emissivity: 0.85,
    meltingPointC: 3550,
    ignitionTemperatureC: 700,
    burnRate: 0.05,
    electricalConductivity: 1e5,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'sulfur',
    name: 'Sulfur',
    color: [0.95, 0.9, 0.25, 1.0],
    immovable: false,
    density: 2070,
    friction: 0.5,
    structuralStrength: 0.15,
    thermalConductivity: 0.205,
    specificHeatCapacity: 710,
    meltingPointC: 115,
    boilingPointC: 445,
    ignitionTemperatureC: 232,
    burnRate: 0.5,
    electricalConductivity: 1e-15,
  },

  // ---------------------------------------------------------------
  // Metals
  // ---------------------------------------------------------------
  {
    ...MATERIAL_DEFAULTS,
    id: 'iron',
    name: 'Iron',
    color: [0.56, 0.57, 0.58, 1.0],
    density: 7874,
    friction: 0.5,
    structuralStrength: 0.8,
    thermalConductivity: 80,
    specificHeatCapacity: 449,
    emissivity: 0.3,
    meltingPointC: 1538,
    boilingPointC: 2862,
    electricalConductivity: 1.0e7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'gold',
    name: 'Gold',
    color: [1.0, 0.84, 0.2, 1.0],
    density: 19300,
    friction: 0.4,
    structuralStrength: 0.4,
    thermalConductivity: 318,
    specificHeatCapacity: 129,
    emissivity: 0.02,
    meltingPointC: 1064,
    boilingPointC: 2856,
    chemicalReactivity: 0.02,
    electricalConductivity: 4.1e7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'copper',
    name: 'Copper',
    color: [0.72, 0.45, 0.2, 1.0],
    density: 8960,
    friction: 0.4,
    structuralStrength: 0.5,
    thermalConductivity: 401,
    specificHeatCapacity: 385,
    emissivity: 0.04,
    meltingPointC: 1085,
    boilingPointC: 2562,
    chemicalReactivity: 0.15,
    electricalConductivity: 5.96e7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'aluminum',
    name: 'Aluminum',
    color: [0.83, 0.83, 0.85, 1.0],
    density: 2700,
    friction: 0.4,
    structuralStrength: 0.45,
    thermalConductivity: 237,
    specificHeatCapacity: 897,
    emissivity: 0.09,
    meltingPointC: 660,
    boilingPointC: 2470,
    chemicalReactivity: 0.3,
    electricalConductivity: 3.5e7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'lead',
    name: 'Lead',
    color: [0.35, 0.35, 0.4, 1.0],
    density: 11340,
    friction: 0.6,
    structuralStrength: 0.15,
    thermalConductivity: 35,
    specificHeatCapacity: 128,
    emissivity: 0.28,
    meltingPointC: 327.5,
    boilingPointC: 1749,
    chemicalReactivity: 0.2,
    electricalConductivity: 4.8e6,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'titanium',
    name: 'Titanium',
    color: [0.75, 0.73, 0.7, 1.0],
    density: 4506,
    friction: 0.45,
    structuralStrength: 0.85,
    thermalConductivity: 21.9,
    specificHeatCapacity: 523,
    emissivity: 0.19,
    meltingPointC: 1668,
    boilingPointC: 3287,
    chemicalReactivity: 0.15,
    electricalConductivity: 2.6e6,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'steel',
    name: 'Steel',
    color: [0.6, 0.61, 0.63, 1.0],
    density: 7850,
    friction: 0.45,
    structuralStrength: 0.95,
    thermalConductivity: 50,
    specificHeatCapacity: 490,
    emissivity: 0.3,
    meltingPointC: 1425,
    boilingPointC: 2862,
    chemicalReactivity: 0.2,
    electricalConductivity: 6.99e6,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'silver',
    name: 'Silver',
    color: [0.92, 0.92, 0.92, 1.0],
    density: 10490,
    friction: 0.4,
    structuralStrength: 0.35,
    thermalConductivity: 429,
    specificHeatCapacity: 235,
    emissivity: 0.02,
    meltingPointC: 962,
    boilingPointC: 2162,
    chemicalReactivity: 0.1,
    electricalConductivity: 6.3e7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'tin',
    name: 'Tin',
    color: [0.75, 0.76, 0.78, 1.0],
    density: 7310,
    friction: 0.4,
    structuralStrength: 0.25,
    thermalConductivity: 66.6,
    specificHeatCapacity: 227,
    emissivity: 0.05,
    meltingPointC: 232,
    boilingPointC: 2602,
    chemicalReactivity: 0.15,
    electricalConductivity: 9.17e6,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'zinc',
    name: 'Zinc',
    color: [0.7, 0.7, 0.73, 1.0],
    density: 7140,
    friction: 0.45,
    structuralStrength: 0.3,
    thermalConductivity: 116,
    specificHeatCapacity: 388,
    emissivity: 0.25,
    meltingPointC: 420,
    boilingPointC: 907,
    chemicalReactivity: 0.35,
    electricalConductivity: 1.69e7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'nickel',
    name: 'Nickel',
    color: [0.72, 0.72, 0.7, 1.0],
    density: 8908,
    friction: 0.45,
    structuralStrength: 0.6,
    thermalConductivity: 90.9,
    specificHeatCapacity: 444,
    emissivity: 0.11,
    meltingPointC: 1455,
    boilingPointC: 2913,
    chemicalReactivity: 0.15,
    electricalConductivity: 1.43e7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'bronze',
    name: 'Bronze',
    color: [0.65, 0.44, 0.25, 1.0],
    density: 8800,
    friction: 0.45,
    structuralStrength: 0.65,
    thermalConductivity: 60,
    specificHeatCapacity: 380,
    emissivity: 0.3,
    meltingPointC: 950,
    boilingPointC: null,
    chemicalReactivity: 0.1,
    electricalConductivity: 1e7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'brass',
    name: 'Brass',
    color: [0.85, 0.7, 0.35, 1.0],
    density: 8500,
    friction: 0.4,
    structuralStrength: 0.6,
    thermalConductivity: 109,
    specificHeatCapacity: 380,
    emissivity: 0.3,
    meltingPointC: 930,
    boilingPointC: null,
    chemicalReactivity: 0.1,
    electricalConductivity: 1.5e7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'platinum',
    name: 'Platinum',
    color: [0.82, 0.82, 0.85, 1.0],
    density: 21450,
    friction: 0.4,
    structuralStrength: 0.5,
    thermalConductivity: 71.6,
    specificHeatCapacity: 133,
    emissivity: 0.05,
    meltingPointC: 1768,
    boilingPointC: 3825,
    chemicalReactivity: 0.02,
    electricalConductivity: 9.4e6,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'uranium',
    name: 'Uranium',
    color: [0.45, 0.55, 0.35, 1.0],
    density: 19050,
    friction: 0.45,
    structuralStrength: 0.5,
    thermalConductivity: 27.5,
    specificHeatCapacity: 116,
    emissivity: 0.15,
    meltingPointC: 1132,
    boilingPointC: 4131,
    chemicalReactivity: 0.4,
    electricalConductivity: 3.6e6,
    halfLifeSeconds: 1.41e17,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'tungsten',
    name: 'Tungsten',
    color: [0.5, 0.5, 0.52, 1.0],
    density: 19300,
    friction: 0.4,
    structuralStrength: 0.95,
    thermalConductivity: 173,
    specificHeatCapacity: 134,
    emissivity: 0.15,
    meltingPointC: 3422,
    boilingPointC: 5555,
    chemicalReactivity: 0.05,
    electricalConductivity: 1.79e7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'cobalt',
    name: 'Cobalt',
    color: [0.6, 0.6, 0.65, 1.0],
    density: 8900,
    friction: 0.45,
    structuralStrength: 0.65,
    thermalConductivity: 100,
    specificHeatCapacity: 420,
    emissivity: 0.2,
    meltingPointC: 1495,
    boilingPointC: 2927,
    chemicalReactivity: 0.2,
    electricalConductivity: 1.6e7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'magnesium',
    name: 'Magnesium',
    color: [0.78, 0.78, 0.8, 1.0],
    density: 1738,
    friction: 0.4,
    structuralStrength: 0.4,
    thermalConductivity: 156,
    specificHeatCapacity: 1023,
    emissivity: 0.07,
    meltingPointC: 650,
    boilingPointC: 1090,
    chemicalReactivity: 0.5,
    ignitionTemperatureC: 473,
    burnRate: 0.9,
    explosiveness: 0.2,
    electricalConductivity: 2.3e7,
  },

  // ---------------------------------------------------------------
  // Organic / biological
  // ---------------------------------------------------------------
  {
    ...MATERIAL_DEFAULTS,
    id: 'oak_wood',
    name: 'Oak Wood',
    color: [0.45, 0.32, 0.18, 1.0],
    density: 750,
    friction: 0.55,
    structuralStrength: 0.6,
    thermalConductivity: 0.17,
    specificHeatCapacity: 2400,
    ignitionTemperatureC: 300,
    burnRate: 0.4,
    absorptionCapacity: 0.3,
    electricalConductivity: 1e-14,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'pine_wood',
    name: 'Pine Wood',
    color: [0.65, 0.5, 0.3, 1.0],
    density: 500,
    friction: 0.5,
    structuralStrength: 0.4,
    thermalConductivity: 0.12,
    specificHeatCapacity: 2300,
    ignitionTemperatureC: 280,
    burnRate: 0.6,
    absorptionCapacity: 0.35,
    electricalConductivity: 1e-14,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'bone',
    name: 'Bone',
    color: [0.9, 0.87, 0.78, 1.0],
    density: 1900,
    friction: 0.5,
    structuralStrength: 0.6,
    thermalConductivity: 0.4,
    specificHeatCapacity: 1300,
    meltingPointC: null,
    ignitionTemperatureC: 400,
    burnRate: 0.1,
    absorptionCapacity: 0.1,
    electricalConductivity: 1e-12,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'leather',
    name: 'Leather',
    color: [0.42, 0.28, 0.18, 1.0],
    density: 860,
    friction: 0.6,
    structuralStrength: 0.4,
    thermalConductivity: 0.15,
    specificHeatCapacity: 1500,
    ignitionTemperatureC: 212,
    burnRate: 0.35,
    absorptionCapacity: 0.4,
    electricalConductivity: 1e-11,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'paper',
    name: 'Paper',
    color: [0.95, 0.94, 0.9, 1.0],
    density: 800,
    friction: 0.4,
    structuralStrength: 0.05,
    thermalConductivity: 0.05,
    specificHeatCapacity: 1340,
    ignitionTemperatureC: 233,
    burnRate: 0.9,
    absorptionCapacity: 0.6,
    electricalConductivity: 1e-12,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'cotton',
    name: 'Cotton',
    color: [0.96, 0.96, 0.94, 1.0],
    density: 300,
    friction: 0.6,
    structuralStrength: 0.05,
    thermalConductivity: 0.04,
    specificHeatCapacity: 1300,
    ignitionTemperatureC: 210,
    burnRate: 0.8,
    absorptionCapacity: 0.7,
    electricalConductivity: 1e-13,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'rubber',
    name: 'Rubber',
    color: [0.12, 0.1, 0.1, 1.0],
    density: 920,
    friction: 0.9,
    structuralStrength: 0.5,
    thermalConductivity: 0.13,
    specificHeatCapacity: 1900,
    meltingPointC: null,
    boilingPointC: null,
    ignitionTemperatureC: 260,
    burnRate: 0.5,
    absorptionCapacity: 0.02,
    electricalConductivity: 1e-15,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'leaves',
    name: 'Dry Leaves',
    color: [0.65, 0.42, 0.15, 1.0],
    density: 200,
    friction: 0.3,
    structuralStrength: 0.02,
    thermalConductivity: 0.05,
    specificHeatCapacity: 1350,
    ignitionTemperatureC: 200,
    burnRate: 0.85,
    absorptionCapacity: 0.2,
    electricalConductivity: 1e-11,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'charcoal',
    name: 'Charcoal',
    color: [0.1, 0.09, 0.08, 1.0],
    density: 210,
    friction: 0.5,
    structuralStrength: 0.1,
    thermalConductivity: 0.08,
    specificHeatCapacity: 1000,
    ignitionTemperatureC: 350,
    burnRate: 0.3,
    absorptionCapacity: 0.5,
    electricalConductivity: 2e2,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'wax',
    name: 'Wax',
    color: [0.92, 0.9, 0.82, 1.0],
    density: 900,
    friction: 0.3,
    structuralStrength: 0.1,
    thermalConductivity: 0.25,
    specificHeatCapacity: 2500,
    meltingPointC: 55,
    boilingPointC: 370,
    ignitionTemperatureC: 245,
    burnRate: 0.6,
    electricalConductivity: 1e-15,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'ice',
    name: 'Ice',
    color: [0.8, 0.9, 0.98, 1.0],
    density: 917,
    friction: 0.05,
    structuralStrength: 0.3,
    thermalConductivity: 2.18,
    specificHeatCapacity: 2050,
    emissivity: 0.97,
    meltingPointC: 0,
    boilingPointC: null,
    electricalConductivity: 1e-7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'snow',
    name: 'Snow',
    color: [0.97, 0.97, 1.0, 1.0],
    density: 100,
    friction: 0.2,
    structuralStrength: 0.02,
    thermalConductivity: 0.05,
    specificHeatCapacity: 2090,
    emissivity: 0.97,
    meltingPointC: 0,
    boilingPointC: null,
    absorptionCapacity: 0.1,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'wool',
    name: 'Wool',
    color: [0.9, 0.88, 0.8, 1.0],
    density: 200,
    friction: 0.7,
    structuralStrength: 0.05,
    thermalConductivity: 0.04,
    specificHeatCapacity: 1360,
    ignitionTemperatureC: 570,
    burnRate: 0.2,
    absorptionCapacity: 0.6,
    electricalConductivity: 1e-13,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'silk',
    name: 'Silk',
    color: [0.92, 0.9, 0.85, 1.0],
    density: 300,
    friction: 0.25,
    structuralStrength: 0.1,
    thermalConductivity: 0.05,
    specificHeatCapacity: 1380,
    ignitionTemperatureC: 460,
    burnRate: 0.3,
    absorptionCapacity: 0.3,
    electricalConductivity: 1e-13,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'straw',
    name: 'Straw',
    color: [0.82, 0.7, 0.35, 1.0],
    density: 120,
    friction: 0.35,
    structuralStrength: 0.03,
    thermalConductivity: 0.05,
    specificHeatCapacity: 1500,
    ignitionTemperatureC: 220,
    burnRate: 0.9,
    absorptionCapacity: 0.4,
    electricalConductivity: 1e-12,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'peat',
    name: 'Peat',
    color: [0.25, 0.18, 0.12, 1.0],
    density: 400,
    friction: 0.5,
    structuralStrength: 0.1,
    thermalConductivity: 0.06,
    specificHeatCapacity: 1900,
    acidity: 4,
    ignitionTemperatureC: 250,
    burnRate: 0.35,
    absorptionCapacity: 0.6,
    electricalConductivity: 1e-8,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'moss',
    name: 'Moss',
    color: [0.25, 0.5, 0.2, 1.0],
    density: 150,
    friction: 0.4,
    structuralStrength: 0.02,
    thermalConductivity: 0.05,
    specificHeatCapacity: 3000,
    acidity: 5.5,
    ignitionTemperatureC: 300,
    burnRate: 0.2,
    absorptionCapacity: 0.8,
    electricalConductivity: 1e-6,
  },

  // ---------------------------------------------------------------
  // Granular / particulate
  // ---------------------------------------------------------------
  {
    ...MATERIAL_DEFAULTS,
    id: 'sand',
    name: 'Sand',
    color: [0.76, 0.7, 0.5, 1.0],
    matterState: 'solid',
    immovable: false,
    density: 1600,
    friction: 0.5,
    structuralStrength: 0.2,
    thermalConductivity: 0.3,
    specificHeatCapacity: 830,
    meltingPointC: 1710,
    absorptionCapacity: 0.15,
    electricalConductivity: 1e-12,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'gravel',
    name: 'Gravel',
    color: [0.55, 0.53, 0.5, 1.0],
    density: 1800,
    friction: 0.45,
    structuralStrength: 0.25,
    thermalConductivity: 0.5,
    specificHeatCapacity: 850,
    meltingPointC: 1200,
    absorptionCapacity: 0.05,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'dry_soil',
    name: 'Dry Soil',
    color: [0.35, 0.25, 0.15, 1.0],
    density: 1300,
    friction: 0.55,
    structuralStrength: 0.1,
    thermalConductivity: 0.3,
    specificHeatCapacity: 800,
    meltingPointC: null,
    absorptionCapacity: 0.35,
    electricalConductivity: 1e-4,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'ash',
    name: 'Ash',
    color: [0.75, 0.74, 0.72, 1.0],
    density: 700,
    friction: 0.3,
    structuralStrength: 0.02,
    thermalConductivity: 0.1,
    specificHeatCapacity: 900,
    meltingPointC: null,
    acidity: 10,
    absorptionCapacity: 0.3,
    electricalConductivity: 1e-5,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'table_salt',
    name: 'Table Salt',
    color: [0.96, 0.96, 0.95, 1.0],
    density: 1200,
    friction: 0.35,
    structuralStrength: 0.05,
    thermalConductivity: 0.5,
    specificHeatCapacity: 880,
    meltingPointC: 801,
    boilingPointC: 1465,
    solubility: 1.0,
    absorptionCapacity: 0.1,
    electricalConductivity: 1e-7,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'sugar',
    name: 'Sugar',
    color: [0.97, 0.97, 0.95, 1.0],
    density: 850,
    friction: 0.35,
    structuralStrength: 0.05,
    thermalConductivity: 0.3,
    specificHeatCapacity: 1250,
    meltingPointC: 186,
    solubility: 1.0,
    ignitionTemperatureC: 410,
    burnRate: 0.3,
    absorptionCapacity: 0.05,
    electricalConductivity: 1e-13,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'gunpowder',
    name: 'Gunpowder',
    color: [0.2, 0.2, 0.22, 1.0],
    density: 1700,
    friction: 0.4,
    structuralStrength: 0.05,
    thermalConductivity: 0.3,
    specificHeatCapacity: 1000,
    meltingPointC: null,
    chemicalReactivity: 0.7,
    ignitionTemperatureC: 170,
    burnRate: 1.0,
    explosiveness: 0.85,
    absorptionCapacity: 0.1,
    electricalConductivity: 1e-8,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'cement_powder',
    name: 'Cement Powder',
    color: [0.65, 0.64, 0.62, 1.0],
    density: 1440,
    friction: 0.6,
    structuralStrength: 0.05,
    thermalConductivity: 0.29,
    specificHeatCapacity: 750,
    meltingPointC: 1450,
    acidity: 12,
    chemicalReactivity: 0.4,
    absorptionCapacity: 0.4,
    electricalConductivity: 1e-8,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'flour',
    name: 'Flour',
    color: [0.94, 0.92, 0.85, 1.0],
    density: 593,
    friction: 0.3,
    structuralStrength: 0.02,
    thermalConductivity: 0.1,
    specificHeatCapacity: 1800,
    meltingPointC: null,
    ignitionTemperatureC: 380,
    burnRate: 0.5,
    explosiveness: 0.4,
    absorptionCapacity: 0.5,
    electricalConductivity: 1e-11,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'sawdust',
    name: 'Sawdust',
    color: [0.7, 0.55, 0.35, 1.0],
    density: 210,
    friction: 0.4,
    structuralStrength: 0.02,
    thermalConductivity: 0.08,
    specificHeatCapacity: 1700,
    meltingPointC: null,
    ignitionTemperatureC: 260,
    burnRate: 0.7,
    explosiveness: 0.2,
    absorptionCapacity: 0.6,
    electricalConductivity: 1e-13,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'baking_soda',
    name: 'Baking Soda',
    color: [0.96, 0.96, 0.94, 1.0],
    density: 900,
    friction: 0.3,
    structuralStrength: 0.05,
    thermalConductivity: 0.3,
    specificHeatCapacity: 1000,
    meltingPointC: null,
    boilingPointC: null,
    acidity: 9,
    chemicalReactivity: 0.4,
    solubility: 0.6,
    absorptionCapacity: 0.2,
    electricalConductivity: 1e-6,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'iron_filings',
    name: 'Iron Filings',
    color: [0.35, 0.34, 0.33, 1.0],
    density: 3800,
    friction: 0.4,
    structuralStrength: 0.1,
    thermalConductivity: 15,
    specificHeatCapacity: 449,
    meltingPointC: 1538,
    chemicalReactivity: 0.3,
    electricalConductivity: 1e4,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'saltpeter',
    name: 'Saltpeter',
    color: [0.93, 0.93, 0.9, 1.0],
    density: 1100,
    friction: 0.35,
    structuralStrength: 0.05,
    thermalConductivity: 0.5,
    specificHeatCapacity: 950,
    meltingPointC: 334,
    boilingPointC: null,
    chemicalReactivity: 0.5,
    solubility: 0.7,
    absorptionCapacity: 0.1,
    electricalConductivity: 1e-6,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'volcanic_ash',
    name: 'Volcanic Ash',
    color: [0.5, 0.48, 0.46, 1.0],
    density: 1000,
    friction: 0.5,
    structuralStrength: 0.05,
    thermalConductivity: 0.2,
    specificHeatCapacity: 800,
    meltingPointC: 1100,
    acidity: 6,
    absorptionCapacity: 0.1,
    electricalConductivity: 1e-8,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'rust',
    name: 'Rust',
    color: [0.55, 0.27, 0.15, 1.0],
    density: 3000,
    friction: 0.5,
    structuralStrength: 0.05,
    thermalConductivity: 0.6,
    specificHeatCapacity: 650,
    meltingPointC: 1565,
    chemicalReactivity: 0.1,
    absorptionCapacity: 0.1,
    electricalConductivity: 1e-2,
  },

  // ---------------------------------------------------------------
  // Manufactured / synthetic
  // ---------------------------------------------------------------
  {
    ...MATERIAL_DEFAULTS,
    id: 'glass',
    name: 'Glass',
    color: [0.85, 0.92, 0.9, 1.0],
    density: 2500,
    friction: 0.2,
    structuralStrength: 0.3,
    thermalConductivity: 1.0,
    specificHeatCapacity: 840,
    meltingPointC: 1500,
    electricalConductivity: 1e-12,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'concrete',
    name: 'Concrete',
    color: [0.62, 0.6, 0.58, 1.0],
    immovable: true,
    density: 2400,
    friction: 0.7,
    structuralStrength: 0.85,
    thermalConductivity: 1.7,
    specificHeatCapacity: 880,
    meltingPointC: 1450,
    acidity: 12,
    absorptionCapacity: 0.15,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'brick',
    name: 'Brick',
    color: [0.65, 0.32, 0.22, 1.0],
    immovable: true,
    density: 1900,
    friction: 0.65,
    structuralStrength: 0.7,
    thermalConductivity: 0.6,
    specificHeatCapacity: 840,
    meltingPointC: 1500,
    absorptionCapacity: 0.2,
    electricalConductivity: 1e-9,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'plastic',
    name: 'Plastic',
    color: [0.85, 0.85, 0.88, 1.0],
    density: 1000,
    friction: 0.4,
    structuralStrength: 0.35,
    thermalConductivity: 0.2,
    specificHeatCapacity: 1700,
    meltingPointC: 130,
    ignitionTemperatureC: 350,
    burnRate: 0.5,
    electricalConductivity: 1e-15,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'pvc',
    name: 'PVC',
    color: [0.9, 0.9, 0.88, 1.0],
    density: 1380,
    friction: 0.45,
    structuralStrength: 0.45,
    thermalConductivity: 0.19,
    specificHeatCapacity: 900,
    meltingPointC: 160,
    chemicalReactivity: 0.1,
    ignitionTemperatureC: 450,
    burnRate: 0.15,
    electricalConductivity: 1e-15,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'asphalt',
    name: 'Asphalt',
    color: [0.1, 0.1, 0.1, 1.0],
    immovable: true,
    density: 2360,
    friction: 0.75,
    structuralStrength: 0.5,
    thermalConductivity: 0.75,
    specificHeatCapacity: 920,
    meltingPointC: 120,
    ignitionTemperatureC: 480,
    burnRate: 0.2,
    absorptionCapacity: 0.05,
    electricalConductivity: 1e-10,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'styrofoam',
    name: 'Styrofoam',
    color: [0.96, 0.96, 0.96, 1.0],
    density: 30,
    friction: 0.5,
    structuralStrength: 0.05,
    thermalConductivity: 0.033,
    specificHeatCapacity: 1300,
    meltingPointC: 240,
    ignitionTemperatureC: 345,
    burnRate: 0.7,
    absorptionCapacity: 0.02,
    electricalConductivity: 1e-16,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'ceramic',
    name: 'Ceramic',
    color: [0.92, 0.9, 0.86, 1.0],
    immovable: true,
    density: 2400,
    friction: 0.3,
    structuralStrength: 0.6,
    thermalConductivity: 1.5,
    specificHeatCapacity: 850,
    meltingPointC: 1700,
    absorptionCapacity: 0.05,
    electricalConductivity: 1e-13,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'fiberglass',
    name: 'Fiberglass',
    color: [0.88, 0.86, 0.7, 1.0],
    density: 1900,
    friction: 0.5,
    structuralStrength: 0.7,
    thermalConductivity: 0.3,
    specificHeatCapacity: 900,
    meltingPointC: null,
    ignitionTemperatureC: 400,
    burnRate: 0.3,
    absorptionCapacity: 0.05,
    electricalConductivity: 1e-13,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'neoprene',
    name: 'Neoprene',
    color: [0.12, 0.12, 0.13, 1.0],
    density: 1230,
    friction: 0.85,
    structuralStrength: 0.4,
    thermalConductivity: 0.2,
    specificHeatCapacity: 2140,
    meltingPointC: null,
    ignitionTemperatureC: 320,
    burnRate: 0.3,
    absorptionCapacity: 0.05,
    electricalConductivity: 1e-13,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'plywood',
    name: 'Plywood',
    color: [0.72, 0.58, 0.38, 1.0],
    density: 600,
    friction: 0.5,
    structuralStrength: 0.5,
    thermalConductivity: 0.13,
    specificHeatCapacity: 1600,
    meltingPointC: null,
    ignitionTemperatureC: 300,
    burnRate: 0.55,
    absorptionCapacity: 0.25,
    electricalConductivity: 1e-13,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'epoxy_resin',
    name: 'Epoxy Resin',
    color: [0.85, 0.75, 0.5, 1.0],
    density: 1150,
    friction: 0.3,
    structuralStrength: 0.55,
    thermalConductivity: 0.2,
    specificHeatCapacity: 1000,
    meltingPointC: null,
    ignitionTemperatureC: 400,
    burnRate: 0.3,
    electricalConductivity: 1e-14,
  },

  // ---------------------------------------------------------------
  // Exotic / special-property showcase
  // ---------------------------------------------------------------
  {
    ...MATERIAL_DEFAULTS,
    id: 'tnt',
    name: 'TNT',
    color: [0.85, 0.78, 0.4, 1.0],
    density: 1654,
    friction: 0.4,
    structuralStrength: 0.3,
    thermalConductivity: 0.2,
    specificHeatCapacity: 1460,
    meltingPointC: 80.4,
    boilingPointC: null,
    chemicalReactivity: 0.6,
    ignitionTemperatureC: 295,
    burnRate: 0.9,
    explosiveness: 1.0,
    electricalConductivity: 1e-12,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'nitroglycerin',
    name: 'Nitroglycerin',
    color: [0.9, 0.85, 0.6, 1.0],
    matterState: 'liquid',
    density: 1600,
    viscosity: 0.036,
    friction: 0,
    structuralStrength: 0.05,
    thermalConductivity: 0.25,
    specificHeatCapacity: 1500,
    meltingPointC: 13,
    boilingPointC: null,
    chemicalReactivity: 0.95,
    ignitionTemperatureC: 50,
    burnRate: 1.0,
    explosiveness: 1.0,
    electricalConductivity: 1e-11,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'sponge',
    name: 'Sponge',
    color: [0.85, 0.75, 0.45, 1.0],
    density: 150,
    friction: 0.6,
    structuralStrength: 0.02,
    thermalConductivity: 0.06,
    specificHeatCapacity: 1400,
    meltingPointC: null,
    ignitionTemperatureC: 300,
    burnRate: 0.4,
    absorptionCapacity: 0.95,
    electricalConductivity: 1e-12,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'phosphorus',
    name: 'White Phosphorus',
    color: [0.92, 0.9, 0.75, 1.0],
    density: 1823,
    friction: 0.3,
    structuralStrength: 0.1,
    thermalConductivity: 0.24,
    specificHeatCapacity: 770,
    meltingPointC: 44.1,
    boilingPointC: 280.5,
    chemicalReactivity: 0.95,
    ignitionTemperatureC: 30,
    burnRate: 0.9,
    explosiveness: 0.3,
    electricalConductivity: 1e-10,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'dry_ice',
    name: 'Dry Ice',
    color: [0.9, 0.95, 0.97, 1.0],
    density: 1600,
    friction: 0.1,
    structuralStrength: 0.15,
    thermalConductivity: 0.15,
    specificHeatCapacity: 1170,
    meltingPointC: -78.5,
    boilingPointC: null,
    electricalConductivity: 1e-14,
  },

  // ---------------------------------------------------------------
  // Gases (data-only - gas movement not yet implemented)
  // ---------------------------------------------------------------
  {
    ...MATERIAL_DEFAULTS,
    id: 'air',
    name: 'Air',
    color: [0.85, 0.92, 1.0, 1.0],
    matterState: 'gas',
    density: 1.2,
    viscosity: 1.8e-5,
    friction: 0,
    structuralStrength: 0,
    thermalConductivity: 0.026,
    specificHeatCapacity: 1005,
    emissivity: 0.01,
    meltingPointC: null,
    boilingPointC: null,
    electricalConductivity: 1e-15,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'steam',
    name: 'Steam',
    color: [0.92, 0.94, 0.96, 1.0],
    matterState: 'gas',
    density: 0.6,
    viscosity: 1.2e-5,
    friction: 0,
    structuralStrength: 0,
    thermalConductivity: 0.025,
    specificHeatCapacity: 2080,
    emissivity: 0.95,
    meltingPointC: null,
    boilingPointC: null,
    electricalConductivity: 1e-4,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'smoke',
    name: 'Smoke',
    color: [0.3, 0.3, 0.32, 1.0],
    matterState: 'gas',
    density: 0.3,
    viscosity: 2e-5,
    friction: 0,
    structuralStrength: 0,
    thermalConductivity: 0.03,
    specificHeatCapacity: 1000,
    emissivity: 0.95,
    meltingPointC: null,
    boilingPointC: null,
    absorptionCapacity: 0,
    electricalConductivity: 1e-8,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'methane',
    name: 'Methane',
    color: [0.8, 0.88, 0.95, 1.0],
    matterState: 'gas',
    density: 0.657,
    viscosity: 1.1e-5,
    friction: 0,
    structuralStrength: 0,
    thermalConductivity: 0.034,
    specificHeatCapacity: 2220,
    meltingPointC: -182.5,
    boilingPointC: -161.5,
    ignitionTemperatureC: 580,
    burnRate: 0.9,
    explosiveness: 0.5,
    electricalConductivity: 1e-15,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'carbon_dioxide',
    name: 'Carbon Dioxide',
    color: [0.9, 0.9, 0.9, 1.0],
    matterState: 'gas',
    density: 1.98,
    viscosity: 1.47e-5,
    friction: 0,
    structuralStrength: 0,
    thermalConductivity: 0.0166,
    specificHeatCapacity: 844,
    meltingPointC: null,
    boilingPointC: -78.5,
    acidity: 5.6,
    electricalConductivity: 1e-15,
  },
  {
    ...MATERIAL_DEFAULTS,
    id: 'nitrogen_gas',
    name: 'Nitrogen',
    color: [0.88, 0.92, 0.98, 1.0],
    matterState: 'gas',
    density: 1.165,
    viscosity: 1.76e-5,
    friction: 0,
    structuralStrength: 0,
    thermalConductivity: 0.026,
    specificHeatCapacity: 1040,
    meltingPointC: -210,
    boilingPointC: -196,
    electricalConductivity: 1e-15,
  },
];
